### ISSUE TITLE
Feature Request : Inkycal weather - consider local timezone

### ISSUE THREAD

**Issue by ZardoZzZz** [aceinnolab/Inkycal#241]
The issue I have is the daily weather is not showing the weather for today but its showing the weather for tommorow onwards (in the morning it's showing the correct weather for today but at about 2pm it changes the weather for tommorows weather.

**Comment by aceisace** [comment]
Apologies for getting back so late, I'm working on this issue now, could you provide the timezone for your place? Then I can reproduce this error 👍

**Comment by ZardoZzZz** [comment]
Hi Ace,

Thanks for looking into this .. my time zone is Vancouver(Canada) so it’s Pacific standard time (-8 GMT)
