### ISSUE TITLE
[Bug]: Red circle and frame off center since 2.0.3 (calendar_module)

### ISSUE THREAD

**Issue by mygrexit** [aceinnolab/Inkycal#281]
**Describe the bug**

This issue is regarding the calendar module:

The red circle around the current day and the border lines around days with events are off center. 

Also: the Name of the month has no space underneath and the event list underneath the calendar looks kinda "cut off".

I looks like a "formatting" problem in general.

I can only speak for the 12.48 waveshare display.

**To Reproduce**

Install new update.

**Expected behavior**

As before. Centered frame and centered red dot.

**Screenshots**

Photo.

![foto_no_exif](https://github.com/aceinnolab/Inkycal/assets/33792951/b58c2d2d-9720-4d19-9407-0c5f0598048f)

**Comment by aceisace** [comment]
@mygrexit May I ask you to test the issue with the latest version of Inkycal? 
To update, you can run:
```sh
sudo apt-get install wkhtmltopdf -y
cd ~/Inkycal
git pull
source venv/bin/activate
pip install -r requirements.txt
# To test if Inkycal is still running fine:
python inky_run.py
```

If all works well, you can then reboot and check if the bug still remains

**Comment by mygrexit** [comment]
Unfortunately not @aceisace, it looks bettet but it is still off. Going to send a picture tommorow since i don't have a phone near me.

**Comment by mygrexit** [comment]
Here you go @aceisace 
![20231125_121926](https://github.com/aceinnolab/Inkycal/assets/33792951/f8ee8446-95d1-435a-8866-1b153371ca3e)
![20231125_121926~2](https://github.com/aceinnolab/Inkycal/assets/33792951/45a0f33e-fdd7-40af-8f9e-2bd7d7756914)

**Comment by mygrexit** [comment]
Here is how it looks a single module

![20231125_222449](https://github.com/aceinnolab/Inkycal/assets/33792951/c629fba7-ffb9-4d35-b800-bd7765b9dc4d)

**Comment by aceisace** [comment]
Thanks for the feedback @mygrexit . Thanks to these images, I can figure out roughly where to look for the issue 👍. I'll push a fix for this in a separate branch before merging into main

**Comment by mygrexit** [comment]
Hello @aceisace, have you had the chance to have a look or is it a bug you won't fix due to the rewrite? :)

**Comment by aceisace** [comment]
Apologies for the late reply. I did have a chance to look into this just now and will push the fix right away. Once the fix is pushed, please run `git pull` in the Inkycal folder and run `sudo reboot` to restart Inkycal. Please let me know it this fixes the issue as I can confirm it works on my end

**Comment by SIDy1993** [comment]
![17074142325603374753600975593942](https://github.com/aceinnolab/Inkycal/assets/155529821/8a0f5dd7-3db5-48cd-afd6-c8cac133a092)

**Comment by mygrexit** [comment]
I can confirm that it looks like in @SIDy1993 comment. Maybe reopen the bug @aceisace :-D
