### ISSUE TITLE
[FEATURE]: add option "clear" to reset display

### ISSUE THREAD

**Issue by the-sim87** [aceinnolab/Inkycal#306]
Should be no big change, run a calibration-cycle with an manual start of inkycal, like:
inky_run.py -clear

Useful when you want to sell a used display or put it offline and private information should not be visible.

**Comment by aceisace** [comment]
Thanks for the feature suggestion @the-sim87 . I've gone ahead to create a new file in the same location as the `inky_run.py` file. This file now be used to clear the display.

The usage is simple too:
```sh
cd ~/Inkycal
source venv/bin/activate
python clear_display.py
```

Once the tests pass on the merge request, it will be merged to main and accessible to everyone. You can then get the latest updates via: 
```sh
cd ~/Inkycal
git pull
```
