### ISSUE TITLE
Display 12,48 inch not updating

### ISSUE THREAD

**Issue by jo9778** [aceinnolab/Inkycal#334]
That bug is in adition to the problem
"Unable to determine board revision from /proc/cpuinfo" 
about one week ago:

After powering up the system , initialisation of the display is done and things were displayed as expected. The ssh console says - "Updating done - Sending display to deepsleep mode"

And then next refresh in xy minutes (as expected). After this time, the system starts up again and tries to refresh but gets stuck in this situation (see screenshot). Interestingly, 9 out of 10 times there is also no different situation after power cycling the whole system.
Maybe there is a little driver or I/O Problem left?

![image](https://github.com/aceinnolab/Inkycal/assets/43312561/4d24b560-3f7d-4730-9230-0b293a4560ba)

The screenshot is from the first startup after the installation process. After power cycling, the system gets stuck within the line "Generating images for all modules...Initialising..EPD init..."

Thank you

**Comment by aceisace** [comment]
This is very likely related to #335 and should therefore be fixed with the latest commit. Please update Inkycal and try again:
```sh
cd ~/Inkycal
git pull
# to test if it works:
source venv/bin/activate
python inky_run.py
```

**Comment by aceisace** [comment]
@jo9778 Can you confirm that it works please so that I can close this issue? Thanks in advance!

**Comment by jo9778** [comment]
Sorry for my late answer. After updating i got the same issue as before. It´s  described here (#331). I decided to replace the RPi4 by a Rpi zero. With this setup, inkycal is working perfect.

**Comment by aceisace** [comment]
Thanks for getting back @jo9778 
In that case, I'll be closing this issue and the other issue can be discussed at #331 👍
