### ISSUE TITLE
[Enhancement]: Improve PiSugar support

### ISSUE THREAD

**Issue by kfezer** [aceinnolab/Inkycal#370]
**Describe the bug**
When trying to run inky_run.py and pysugar board is off, bet this error:
```
21-08-2024 10:44:54 | inkycal.main |  INFO: name : Weather size : 984x256 px
21-08-2024 10:44:54 | inkycal.main |  INFO: PiSugar support enabled.
21-08-2024 10:44:55 | inkycal.main |  INFO: PiSugar battery capacity: None%
Traceback (most recent call last):
  File "/home/inky/Inkycal/inky_run.py", line 43, in <module>
    asyncio.run(run())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/inky/Inkycal/inky_run.py", line 18, in run
    inky = Inkycal(render=True, use_pi_sugar=True, shutdown_after_run=True)
  File "/home/inky/Inkycal/inkycal/main.py", line 168, in __init__
    if self.battery_capacity < 20:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**To Reproduce**
1. With rpi plugged in, run inky_run.py

**Expected behavior**
Should handle the error of type better.

**Comment by aceisace** [comment]
Hi @kfezer and thanks for reporting the issue. Yes, it seems this needs some improvements as the battery level cannot be read if the PiSugar board is off. Would you be willing to help test this functionality as I do not use the PiSugar on my build? 
If yes, I'll have a fix ready soon and will provide you with some instructions on how to test the fix. If it works for you, then this can be made public.
