### ISSUE TITLE
Feeds Module always showing First Item from RSS Feed

### ISSUE THREAD

**Issue by blandfried** [aceinnolab/Inkycal#375]
**Describe the bug**

When using the Feeds module it is only displaying the first item from the feed(s) that are provided to it.

**To Reproduce**
1. Add Feeds Module to `settings.json` 
2. Provide a RSS feed url with multiple items
3. Run Inkycal 
4. See first item only appearing on screen

**Expected behavior**
The Feeds module should be displaying 1-x number of items based on module size provided.

**Screenshots**

![PXL_20240826_1236151712](https://github.com/user-attachments/assets/070c8765-8c9a-4ae7-a8fc-b6b4539afd62)

**Comment by aceisace** [comment]
Thanks for reporting this issue @blandfried . This was just been fixed in #374
