### ISSUE TITLE
[BUG] Web-UI reCAPTCHA "ERROR for site owner: Invalid domain for site key"

### ISSUE THREAD

**Issue by philippnbg** [aceinnolab/Inkycal#376]
**Describe the bug**
Web-UI ist currently defunct as reCAPTCHA is misconfigured so a user is unable to generate settings.json

**To Reproduce**
1. Go to https://inkycal.aceinnolab.com/ui
2. Scroll down to see reCAPTCHA misconfigured

**Screenshots**
![image](https://github.com/user-attachments/assets/3f70717b-4bee-4def-957e-64ea377c23cb)

**Comment by aceisace** [comment]
Thank you very much!
